### ISSUE TITLE
Question about your example/module

### ISSUE THREAD

**Issue by DjebbZ** [andreypopp/cssobjectify#1]
Hello,

I'm trying to understand this module, but can't wrap my head about how it could be useful based on your example. Instead of using this transform and assigning the styles parsed to `style` property of the `div` (inline styles ? really ?), I would have used another transform, [cssify](https://github.com/davidguttman/cssify) that is still `require()`d in my React component code, but instead inject the styles in the head tag, so I can confidently use the styles in it as classes for the React component. In what circumstances should I prefer `cssobjectify` over `cssify` ?

This is not a rant/troll/whatever-bad-attitude. I'm preparing a talk about Browserify for my local user group (http://parisjs.org/) and I'm starting to use it professionally. So basically I'm just evaluating the different possibilities that Browserify and its ecosystem provide.

Thanks in advance.

**Comment by andreypopp** [comment]
Hello,

you are right, this transform doesn't have much utility apart from when you
want to specify some inline styling for React component using CSS syntax.

Good luck with your talk. Browserify is awesome.

On Sun, Feb 9, 2014 at 6:45 PM, Khalid Jebbari notifications@github.comwrote:

> Hello,
> 
> I'm trying to understand this module, but can't wrap my head about how it
> could be useful based on your example. Instead of using this transform and
> assigning the styles parsed to style property of the div (inline styles ?
> really ?), I would have used another transform, cssifyhttps://github.com/davidguttman/cssifythat is still
> require()d in my React component code, but instead inject the styles in
> the head tag, so I can confidently use the styles in it as classes for the
> React component. In what circumstances should I prefer cssobjectify over
> cssify ?
> 
> This is not a rant/troll/whatever-bad-attitude. I'm preparing a talk about
> Browserify for my local user group (http://parisjs.org/) and I'm starting
> to use it professionally. So basically I'm just evaluating the different
> possibilities that Browserify and its ecosystem provide.
> 
> Thanks in advance.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andreypopp/cssobjectify/issues/1
> .

## 

Andrey Popp / 8mayday@gmail.com
