### ISSUE TITLE
support for strings and not just files

### ISSUE THREAD

**Issue by stevenvachon** [andreypopp/cssobjectify#6]
There are other more general purpose uses for this library that would be made possible if it was not locked in to reading files from disk.

**Comment by andreypopp** [comment]
It exposes a single function which takes `filename` and returns a stream in which you can pipe arbitrary content (fro filesystem or in-memory string) and receive processed content. Argument `filename` is only used for error reporting, you can pass there anything. So cssobjectify already supports processing strings.

**Comment by stevenvachon** [comment]
https://github.com/elierotenberg/react-css
